//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained designer file matching the control IDs in NotificationBell.ascx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRoom.WebForms.Controls
{
    public partial class NotificationBell
    {
        protected global::System.Web.UI.WebControls.PlaceHolder PhCount;
    }
}
