//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a part of the ASP.NET Web Application project
//     system. Hand-maintained to match the control IDs declared in Site.Master.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRoom.WebForms
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlHead head;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.PlaceHolder PhNavDashboard;
        protected global::System.Web.UI.WebControls.PlaceHolder PhAuthenticated;
        protected global::System.Web.UI.WebControls.PlaceHolder PhAnonymous;
        protected global::System.Web.UI.WebControls.PlaceHolder PhMobileAuth;
        protected global::System.Web.UI.WebControls.PlaceHolder PhMobileAdminConsole;
        protected global::System.Web.UI.WebControls.PlaceHolder PhMobileAnonymous;
        protected global::System.Web.UI.WebControls.PlaceHolder PhFooterAuth;
        protected global::System.Web.UI.WebControls.PlaceHolder PhFooterAnonymous;
        protected global::System.Web.UI.WebControls.PlaceHolder PhCertificates;
        protected global::System.Web.UI.WebControls.LinkButton LogoutButton;
        protected global::System.Web.UI.WebControls.LinkButton FooterLogoutButton;
        protected global::System.Web.UI.WebControls.PlaceHolder PhAdminConsole;
        protected global::System.Web.UI.WebControls.PlaceHolder PhToast;

        protected global::System.Web.UI.UserControl Bell;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
