//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for the migrated Web Forms page.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRoom.WebForms.Courses
{
    public partial class Details
    {
        protected global::System.Web.UI.WebControls.PlaceHolder CourseNotFound;
        protected global::System.Web.UI.WebControls.PlaceHolder CourseContent;
        protected global::System.Web.UI.WebControls.HiddenField CourseCsrfToken;
        protected global::System.Web.UI.WebControls.Button EnrollButton;
        protected global::System.Web.UI.WebControls.Repeater ModulesRepeater;
        protected global::System.Web.UI.WebControls.Repeater LessonsOutlineRepeater;
        protected global::System.Web.UI.WebControls.Repeater ResourcesRepeater;
    }
}
