//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for the migrated Web Forms page.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRoom.WebForms.Courses
{
    public partial class Index
    {
        protected global::System.Web.UI.WebControls.Repeater CoursesRepeater;
    }
}
